### ISSUE TITLE
Package name disambiguation: same as tvOS package

### ISSUE THREAD

**Issue by jromanos-hiberus** [googleads/swift-package-manager-google-interactive-media-ads-ios#1] opened 2024-01-15 14:45 UTC
We need package name disambiguation as we can't use two packages with the same name. Previously mentioned here https://github.com/googleads/swift-package-manager-google-interactive-media-ads-tvos/issues/1

In order to have support for both iOS and tvOS platforms, these two packages should be called differently (adding a "xxOS" suffix would be a possible solution)

**Comment by gschoppe** [comment] 2024-04-26 18:56
I'm going to close this issue, as a duplicate of the tvOS issue, simply to maintain a single source of truth as we move toward a resolution.

**Closed by gschoppe** 2024-04-26 18:56 UTC
